version: '3'

services:
  server:
    container_name: server-001
    image: localhost/shadow_server:latest
    command: server 1
    volumes:
      - "/data/workspace/project/shadoweditor/build/linux/x64/release/conf/:/usr/local/shadoweditor/server/conf/"
      - "/data/workspace/project/shadoweditor/script/build/:/usr/local/shadoweditor/server/script/"
      - "/data/workspace/project/shadoweditor/build/linux/x64/release/log/:/usr/local/shadoweditor/server/log/"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    restart: always
    privileged: true

networks:
  default:
    name: podman
    driver: bridge
