version: '3'

services:
  server:
    container_name: server-001
    image: localhost/shadowserver:latest
    command:
      - sh
      - -c
      - |
        cd /opt/server
        ./server 1
    volumes:
      - "/data/workspace/project/shadoweditor/build/linux/x64/release/conf/:/usr/local/shadoweditor/server/conf/"
      - "/data/workspace/project/shadoweditor/script/build/:/usr/local/shadoweditor/server/script/"
      - "/data/workspace/project/shadoweditor/build/linux/x64/release/log/:/usr/local/shadoweditor/server/log/"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "37001:37001"
      - "37002:37002"
      - "37003:37003"
      - "37004:37004"
      - "37005:37005"
    restart: always
    privileged: true

networks:
  default:
    name: podman
    driver: bridge
